---

- hosts : all
  become: true
  pre_tasks:

  - name: install updates(RedHat)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"

  - name: install updates(Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:  

  - name: install apache and php  ubuntu
    apt:
      name:
         - apache2
         - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
    
  - name: install apache and php for RedHat
    dnf:
      name: 
         - php
         - httpd
      state: latest
      update_cache: yes
    when: ansible_distribution == "RedHat"

- hosts: db_servers
  become: true
  tasks: 

  - name: install mariadb on RedHat
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution =="RedHat"

  - name: install mariadb on Ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks: 
     - name: install file package
       package: 
            name: samba
            state: latest  
